/**
 * Single home for the CLI's parseArgs option table. main.ts feeds this table
 * to parseArgs; command modules use CliOptionName so a mistyped --flag is a
 * compile error instead of a runtime "option is required" failure.
 */
export const cliOptions = {
  "project-id": { type: "string" },
  "operator-id": { type: "string" },
  "roles-json": { type: "string" },
  "goal-id": { type: "string" },
  "conversation-id": { type: "string" },
  model: { type: "string" },
  text: { type: "string" },
  message: { type: "string" },
  "command-id": { type: "string" },
  "contract-id": { type: "string" },
  "substance-json": { type: "string" },
  "activation-json": { type: "string" },
  "council-json": { type: "string" },
  "brief-json": { type: "string" },
  "packet-json": { type: "string" },
  "plan-json": { type: "string" },
  "bundle-json": { type: "string" },
  "worker-json": { type: "string" },
  "worker-id": { type: "string" },
  "repository-path": { type: "string" },
  "branch-name": { type: "string" },
  "base-revision": { type: "string" },
  "worktree-path": { type: "string" },
  "certification-json": { type: "string" },
  "certification-kind": { type: "string" },
  "review-json": { type: "string" },
  "finding-ids": { type: "string" },
  "evidence-references": { type: "string" },
  "capability-kind": { type: "string" },
  "session-id": { type: "string" },
  "full-access-mode": { type: "string" },
  "correlation-id": { type: "string" },
  kind: { type: "string" },
  "media-type": { type: "string" },
  "content-base64": { type: "string" },
  "content-file": { type: "string" },
  "challenge-id": { type: "string" },
  "correction-request": { type: "string" },
  reason: { type: "string" },
  "plan-version": { type: "string" },
  "department-id": { type: "string" },
  "item-id": { type: "string" },
  "council-id": { type: "string" },
  "content-hash": { type: "string" },
  "expires-at": { type: "string" },
  action: { type: "string" },
  target: { type: "string" },
  "budget-effect-cents": { type: "string" },
  version: { type: "string" },
  "expected-version": { type: "string" },
  "outside-evidence": { type: "boolean", default: false },
  "preview-needed": { type: "boolean", default: false },
  to: { type: "string" },
  after: { type: "string" },
  json: { type: "boolean", default: false },
} as const;

export type CliOptionName = keyof typeof cliOptions;
