-- Phase 4 step 1: task-scoped environment recipes and lifecycle records. Additive only.
CREATE TABLE IF NOT EXISTS environments (
 environment_id uuid PRIMARY KEY, recipe_version integer NOT NULL CHECK (recipe_version > 0), goal_id uuid NOT NULL REFERENCES goals(goal_id), department_id text NOT NULL CHECK (btrim(department_id) <> ''), worker_id uuid NOT NULL, project_id uuid NOT NULL, mission_id uuid NOT NULL,
 environment_type text NOT NULL CHECK (environment_type IN ('local_worktree','container_sandbox','browser_automation','enrolled_device')),
 recipe jsonb NOT NULL CHECK (jsonb_typeof(recipe) = 'object'), resolved_inputs jsonb NOT NULL CHECK (jsonb_typeof(resolved_inputs) = 'object'), capabilities jsonb NOT NULL CHECK (jsonb_typeof(capabilities) = 'array'), boundaries jsonb NOT NULL CHECK (jsonb_typeof(boundaries) = 'object'), secrets_references jsonb NOT NULL CHECK (jsonb_typeof(secrets_references) = 'array'), resource_ceilings jsonb NOT NULL CHECK (jsonb_typeof(resource_ceilings) = 'object'), expires_at timestamptz NOT NULL,
 state text NOT NULL CHECK (state IN ('requested','building','ready','unusable','expired','cleaning','cleaned')), setup_log jsonb NOT NULL CHECK (jsonb_typeof(setup_log) = 'array'), health jsonb NOT NULL CHECK (jsonb_typeof(health) = 'object'), content_identity char(64) NOT NULL CHECK (content_identity ~ '^[0-9a-f]{64}$'), cleanup jsonb NOT NULL CHECK (jsonb_typeof(cleanup) = 'object'), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), retention retention_class NOT NULL DEFAULT 'project_lifetime'
);
CREATE INDEX IF NOT EXISTS environments_goal_idx ON environments(goal_id, created_at);
CREATE INDEX IF NOT EXISTS environments_expiry_idx ON environments(expires_at) WHERE state IN ('requested','building','ready');
CREATE OR REPLACE FUNCTION reject_environment_identity_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.environment_id IS DISTINCT FROM OLD.environment_id OR NEW.recipe_version IS DISTINCT FROM OLD.recipe_version OR NEW.goal_id IS DISTINCT FROM OLD.goal_id OR NEW.department_id IS DISTINCT FROM OLD.department_id OR NEW.worker_id IS DISTINCT FROM OLD.worker_id OR NEW.project_id IS DISTINCT FROM OLD.project_id OR NEW.mission_id IS DISTINCT FROM OLD.mission_id OR NEW.environment_type IS DISTINCT FROM OLD.environment_type OR NEW.recipe IS DISTINCT FROM OLD.recipe OR NEW.resolved_inputs IS DISTINCT FROM OLD.resolved_inputs OR NEW.content_identity IS DISTINCT FROM OLD.content_identity OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN RAISE EXCEPTION 'Environment identity and recipe are immutable'; END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS environments_identity_immutable ON environments;
CREATE TRIGGER environments_identity_immutable BEFORE UPDATE ON environments FOR EACH ROW EXECUTE FUNCTION reject_environment_identity_mutation();
