import { useState } from "react";
import { Icon } from "../icons.js";

interface RegistryItem {
  name: string;
  tags: string[];
  icon: string;
  sub: string;
  badge: { label: string; className: string };
  meta?: string;
}

const skills: RegistryItem[] = [
  { name: "docx generation", tags: ["docs", "generation"], icon: "file-code", sub: "built-in · used by product, tech", badge: { label: "available", className: "badge-olive" } },
  { name: "data analysis", tags: ["data"], icon: "chart-bar", sub: "built-in · used by intelligence", badge: { label: "available", className: "badge-olive" } },
  { name: "frontend design", tags: ["design", "generation"], icon: "palette", sub: "built-in · used by design", badge: { label: "available", className: "badge-olive" } },
];

const tools: RegistryItem[] = [
  { name: "stripe-webhook-relay mcp", tags: ["payments", "webhook"], icon: "hash", sub: "sha256 8e21c0… · generated by infrastructure worker-2", badge: { label: "certified", className: "badge-olive" }, meta: "reused ×4" },
  { name: "notion-sync mcp", tags: ["sync"], icon: "hash", sub: "sha256 2f9a71… · generated by infrastructure worker-5", badge: { label: "certified", className: "badge-olive" }, meta: "reused ×1" },
  { name: "raw-shell-exec mcp", tags: ["rejected"], icon: "ban", sub: "rejected · missing AuthorizedEffectExecutor wrapper", badge: { label: "rejected", className: "badge-rust" } },
];

function Registry({ items, tagOptions, placeholder }: { items: RegistryItem[]; tagOptions: string[]; placeholder: string }) {
  const [activeTag, setActiveTag] = useState<string | undefined>(undefined);
  const [search, setSearch] = useState("");

  const filtered = items.filter((item) => {
    const matchesTag = activeTag === undefined || item.tags.includes(activeTag);
    const matchesSearch = search === "" || item.name.toLowerCase().includes(search.toLowerCase());
    return matchesTag && matchesSearch;
  });

  return (
    <div className="page-body">
      <div className="reg-toolbar">
        <input className="input" type="text" placeholder={placeholder} value={search} onChange={(event) => setSearch(event.target.value)} />
        <div className="tag-row">
          {tagOptions.map((tag) => (
            <div key={tag} className={`chip${activeTag === tag ? " active" : ""}`} onClick={() => setActiveTag((current) => (current === tag ? undefined : tag))}>{tag}</div>
          ))}
        </div>
      </div>
      {filtered.map((item) => (
        <div key={item.name} className="reg-item">
          <Icon name={item.icon} />
          <div className="reg-item-body">
            <div className="reg-item-title">{item.name}</div>
            <div className="reg-item-sub">{item.sub}</div>
            <div className="reg-item-tags">{item.tags.map((tag) => <span key={tag} className="reg-item-tag">#{tag}</span>)}</div>
          </div>
          <div className="reg-item-meta">
            <span className={`badge ${item.badge.className}`}>{item.badge.label}</span>
            {item.meta !== undefined && <span style={{ fontSize: 10.5, color: "var(--text-muted)" }}>{item.meta}</span>}
          </div>
        </div>
      ))}
    </div>
  );
}

export function Luthiery() {
  const [tab, setTab] = useState<"skills" | "tools">("skills");

  return (
    <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
      <div className="dash-head" style={{ padding: "14px 20px 0" }}><div className="dash-title">luthiery</div></div>
      <div className="dash-sub" style={{ padding: "0 20px" }}>tool &amp; skill workshop · cross-goal registry, owned by infrastructure</div>
      <div className="page-tabs">
        <div className={`page-tab${tab === "skills" ? " on" : ""}`} onClick={() => setTab("skills")}>skills</div>
        <div className={`page-tab${tab === "tools" ? " on" : ""}`} onClick={() => setTab("tools")}>tools</div>
      </div>
      {tab === "skills"
        ? <Registry items={skills} tagOptions={["docs", "data", "design", "generation"]} placeholder="search skills" />
        : <Registry items={tools} tagOptions={["payments", "sync", "webhook", "rejected"]} placeholder="search tools" />}
    </div>
  );
}
