import { randomUUID } from "node:crypto";
import { assertValidEnvironmentRecord, assertValidEnvironmentRecipe, environmentContentIdentity, type EnvironmentRecord, type EnvironmentRecipe, type EnvironmentState, type EnvironmentHealth, type EnvironmentCleanup } from "@maestro/domain";
import type { Pool, PoolClient } from "pg";
import type { GoalLeaseProof } from "./commands.js";

export interface EnvironmentActorContext { readonly actorId: string; readonly sessionRef: string; }
export class EnvironmentError extends Error {}
export class EnvironmentNotFoundError extends EnvironmentError {}

async function authorize(client: PoolClient, goalId: string, proof: GoalLeaseProof, context: EnvironmentActorContext): Promise<void> {
 if (!proof || proof.goalId !== goalId || !context.actorId.trim() || !context.sessionRef.trim()) throw new EnvironmentError("Environment mutation requires matching lease and actor context");
 const result = await client.query("SELECT 1 FROM goal_leases WHERE goal_id=$1 AND owner_id=$2 AND fencing_token=$3::bigint AND expires_at > clock_timestamp() FOR UPDATE", [goalId, proof.ownerId, proof.fencingToken]);
 if (result.rowCount !== 1) throw new EnvironmentError("Environment mutation requires a current Goal lease");
}
function map(row: Record<string, unknown>): EnvironmentRecord {
 const r: EnvironmentRecord = { environmentId: String(row.environment_id), recipeVersion: Number(row.recipe_version), goalId: String(row.goal_id), departmentId: String(row.department_id), workerId: String(row.worker_id), projectId: String(row.project_id), missionId: String(row.mission_id), type: row.environment_type as EnvironmentRecord["type"], recipe: row.recipe as EnvironmentRecord["recipe"], resolvedInputs: row.resolved_inputs as EnvironmentRecord["resolvedInputs"], capabilities: row.capabilities as EnvironmentRecord["capabilities"], boundaries: row.boundaries as EnvironmentRecord["boundaries"], secretsReferences: row.secrets_references as EnvironmentRecord["secretsReferences"], resources: row.resource_ceilings as EnvironmentRecord["resources"], expiresAt: new Date(String(row.expires_at)).toISOString(), state: row.state as EnvironmentState, setupLog: row.setup_log as string[], health: row.health as EnvironmentHealth, contentIdentity: String(row.content_identity), cleanup: row.cleanup as EnvironmentCleanup };
 assertValidEnvironmentRecord(r); return r;
}
const columns="environment_id,recipe_version,goal_id,department_id,worker_id,project_id,mission_id,environment_type,recipe,resolved_inputs,capabilities,boundaries,secrets_references,resource_ceilings,expires_at,state,setup_log,health,content_identity,cleanup";
export async function createEnvironment(pool: Pool, input: Omit<EnvironmentRecord,"environmentId"|"contentIdentity"|"state"|"setupLog"|"health"|"cleanup"> & { recipe: Readonly<Record<string, unknown>>; resolvedInputs: Readonly<Record<string, unknown>> }, proof: GoalLeaseProof, context: EnvironmentActorContext): Promise<EnvironmentRecord> {
 const recipe: EnvironmentRecipe = { recipeVersion: input.recipeVersion, type: input.type, recipe: input.recipe, resolvedInputs: input.resolvedInputs }; assertValidEnvironmentRecipe(recipe);
 const record: EnvironmentRecord = { ...input, environmentId: randomUUID(), contentIdentity: environmentContentIdentity(recipe), state:"requested", setupLog:[], health:{status:"unknown",checkedAt:null,summary:null}, cleanup:{status:"not_scheduled",scheduledAt:null,completedAt:null,ownedResources:[],retainedEvidence:[]} };
 const client=await pool.connect(); try { await client.query("BEGIN"); await authorize(client,input.goalId,proof,context); await client.query(`INSERT INTO environments (${columns}) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14::jsonb,$15,$16,$17::jsonb,$18::jsonb,$19,$20::jsonb)`, [record.environmentId,record.recipeVersion,record.goalId,record.departmentId,record.workerId,record.projectId,record.missionId,record.type,JSON.stringify(record.recipe),JSON.stringify(record.resolvedInputs),JSON.stringify(record.capabilities),JSON.stringify(record.boundaries),JSON.stringify(record.secretsReferences),JSON.stringify(record.resources),record.expiresAt,record.state,JSON.stringify(record.setupLog),JSON.stringify(record.health),record.contentIdentity,JSON.stringify(record.cleanup)]); await client.query("COMMIT"); return record; } catch(e){await client.query("ROLLBACK");throw e} finally{client.release()}
}
async function transition(pool: Pool, id: string, state: EnvironmentState, patch: { setupLog?: readonly string[]; health?: EnvironmentHealth; cleanup?: EnvironmentCleanup }, proof: GoalLeaseProof, context: EnvironmentActorContext): Promise<EnvironmentRecord> { const client=await pool.connect(); try { await client.query("BEGIN"); const old=await client.query<Record<string,unknown>>(`SELECT ${columns} FROM environments WHERE environment_id=$1 FOR UPDATE`,[id]); if(old.rowCount!==1) throw new EnvironmentNotFoundError(id); const current=map(old.rows[0]!); await authorize(client,current.goalId,proof,context); const next={...current,state,setupLog:patch.setupLog??current.setupLog,health:patch.health??current.health,cleanup:patch.cleanup??current.cleanup}; await client.query("UPDATE environments SET state=$2,setup_log=$3::jsonb,health=$4::jsonb,cleanup=$5::jsonb WHERE environment_id=$1",[id,state,JSON.stringify(next.setupLog),JSON.stringify(next.health),JSON.stringify(next.cleanup)]); await client.query("COMMIT"); return next; } catch(e){await client.query("ROLLBACK");throw e} finally{client.release()} }
export const recordEnvironmentBuildFailure=(pool:Pool,id:string,logs:readonly string[],ownedResources:readonly string[],proof:GoalLeaseProof,context:EnvironmentActorContext)=>transition(pool,id,"unusable",{setupLog:logs,cleanup:{status:"scheduled",scheduledAt:new Date().toISOString(),completedAt:null,ownedResources,retainedEvidence:[]}},proof,context);
export const recordEnvironmentHealth=(pool:Pool,id:string,health:EnvironmentHealth,proof:GoalLeaseProof,context:EnvironmentActorContext)=>transition(pool,id,health.status==="healthy"?"ready":"unusable",{health},proof,context);
export const expireEnvironment=(pool:Pool,id:string,proof:GoalLeaseProof,context:EnvironmentActorContext)=>transition(pool,id,"expired",{},proof,context);
export async function scheduleEnvironmentCleanup(pool: Pool, id: string, evidence: readonly string[], proof: GoalLeaseProof, context: EnvironmentActorContext): Promise<EnvironmentRecord> {
 const current = await readEnvironment(pool, id); if (!current) throw new EnvironmentNotFoundError(id);
 return transition(pool, id, "cleaning", { cleanup: { status: "scheduled", scheduledAt: new Date().toISOString(), completedAt: null, ownedResources: current.cleanup.ownedResources, retainedEvidence: evidence } }, proof, context);
}
export async function completeEnvironmentCleanup(pool: Pool, id: string, proof: GoalLeaseProof, context: EnvironmentActorContext): Promise<EnvironmentRecord> {
 const current = await readEnvironment(pool, id); if (!current) throw new EnvironmentNotFoundError(id);
 return transition(pool, id, "cleaned", { cleanup: { ...current.cleanup, status: "completed", completedAt: new Date().toISOString() } }, proof, context);
}
export async function readEnvironment(pool: Pick<Pool,"query">, id:string): Promise<EnvironmentRecord|undefined> { const result=await pool.query<Record<string,unknown>>(`SELECT ${columns} FROM environments WHERE environment_id=$1`,[id]); return result.rowCount===1?map(result.rows[0]!):undefined; }
